//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameChat.Service2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service2.IService2", CallbackContract=typeof(GameChat.Service2.IService2Callback))]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Connect", ReplyAction="http://tempuri.org/IService2/ConnectResponse")]
        void Connect(string user_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Connect", ReplyAction="http://tempuri.org/IService2/ConnectResponse")]
        System.Threading.Tasks.Task ConnectAsync(string user_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Disconnect", ReplyAction="http://tempuri.org/IService2/DisconnectResponse")]
        void Disconnect(string user_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Disconnect", ReplyAction="http://tempuri.org/IService2/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync(string user_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/SendMessageFriend", ReplyAction="http://tempuri.org/IService2/SendMessageFriendResponse")]
        string SendMessageFriend(string message, string sender, string recipient, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/SendMessageFriend", ReplyAction="http://tempuri.org/IService2/SendMessageFriendResponse")]
        System.Threading.Tasks.Task<string> SendMessageFriendAsync(string message, string sender, string recipient, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/SendMessageInRoom", ReplyAction="http://tempuri.org/IService2/SendMessageInRoomResponse")]
        string SendMessageInRoom(int room_id, string sender_name, string message, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/SendMessageInRoom", ReplyAction="http://tempuri.org/IService2/SendMessageInRoomResponse")]
        System.Threading.Tasks.Task<string> SendMessageInRoomAsync(int room_id, string sender_name, string message, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/ban", ReplyAction="http://tempuri.org/IService2/banResponse")]
        string ban(int room_id, string user_name, string game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/ban", ReplyAction="http://tempuri.org/IService2/banResponse")]
        System.Threading.Tasks.Task<string> banAsync(int room_id, string user_name, string game);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Callback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService2/SendMessageFriendCallBack")]
        void SendMessageFriendCallBack(string message, string sender, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService2/SendMessageInRoomCallBack")]
        void SendMessageInRoomCallBack(int room_id, string sender_name, string message, System.DateTime dateTime);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService2/banCallBack")]
        void banCallBack(int room_id, string game);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : GameChat.Service2.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.DuplexClientBase<GameChat.Service2.IService2>, GameChat.Service2.IService2 {
        
        public Service2Client(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public Service2Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public Service2Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Connect(string user_name) {
            base.Channel.Connect(user_name);
        }
        
        public System.Threading.Tasks.Task ConnectAsync(string user_name) {
            return base.Channel.ConnectAsync(user_name);
        }
        
        public void Disconnect(string user_name) {
            base.Channel.Disconnect(user_name);
        }
        
        public System.Threading.Tasks.Task DisconnectAsync(string user_name) {
            return base.Channel.DisconnectAsync(user_name);
        }
        
        public string SendMessageFriend(string message, string sender, string recipient, System.DateTime dateTime) {
            return base.Channel.SendMessageFriend(message, sender, recipient, dateTime);
        }
        
        public System.Threading.Tasks.Task<string> SendMessageFriendAsync(string message, string sender, string recipient, System.DateTime dateTime) {
            return base.Channel.SendMessageFriendAsync(message, sender, recipient, dateTime);
        }
        
        public string SendMessageInRoom(int room_id, string sender_name, string message, System.DateTime dateTime) {
            return base.Channel.SendMessageInRoom(room_id, sender_name, message, dateTime);
        }
        
        public System.Threading.Tasks.Task<string> SendMessageInRoomAsync(int room_id, string sender_name, string message, System.DateTime dateTime) {
            return base.Channel.SendMessageInRoomAsync(room_id, sender_name, message, dateTime);
        }
        
        public string ban(int room_id, string user_name, string game) {
            return base.Channel.ban(room_id, user_name, game);
        }
        
        public System.Threading.Tasks.Task<string> banAsync(int room_id, string user_name, string game) {
            return base.Channel.banAsync(room_id, user_name, game);
        }
    }
}
