//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameChat.Server {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Server.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/login", ReplyAction="http://tempuri.org/IService/loginResponse")]
        string login(string Email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/login", ReplyAction="http://tempuri.org/IService/loginResponse")]
        System.Threading.Tasks.Task<string> loginAsync(string Email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/accountCheckForReg", ReplyAction="http://tempuri.org/IService/accountCheckForRegResponse")]
        string accountCheckForReg(string userName, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/accountCheckForReg", ReplyAction="http://tempuri.org/IService/accountCheckForRegResponse")]
        System.Threading.Tasks.Task<string> accountCheckForRegAsync(string userName, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FriendAdd", ReplyAction="http://tempuri.org/IService/FriendAddResponse")]
        string FriendAdd(string userNameSender, string userNameRecepient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FriendAdd", ReplyAction="http://tempuri.org/IService/FriendAddResponse")]
        System.Threading.Tasks.Task<string> FriendAddAsync(string userNameSender, string userNameRecepient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Reg", ReplyAction="http://tempuri.org/IService/RegResponse")]
        string Reg(string userName, string Email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Reg", ReplyAction="http://tempuri.org/IService/RegResponse")]
        System.Threading.Tasks.Task<string> RegAsync(string userName, string Email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getAccount", ReplyAction="http://tempuri.org/IService/getAccountResponse")]
        string getAccount(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getAccount", ReplyAction="http://tempuri.org/IService/getAccountResponse")]
        System.Threading.Tasks.Task<string> getAccountAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getFriendList", ReplyAction="http://tempuri.org/IService/getFriendListResponse")]
        string[] getFriendList(string userName, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getFriendList", ReplyAction="http://tempuri.org/IService/getFriendListResponse")]
        System.Threading.Tasks.Task<string[]> getFriendListAsync(string userName, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/unfriend", ReplyAction="http://tempuri.org/IService/unfriendResponse")]
        string unfriend(string userNameSender, string userNameFriend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/unfriend", ReplyAction="http://tempuri.org/IService/unfriendResponse")]
        System.Threading.Tasks.Task<string> unfriendAsync(string userNameSender, string userNameFriend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/acceptInvation", ReplyAction="http://tempuri.org/IService/acceptInvationResponse")]
        string acceptInvation(string userNameSender, string userNameFriend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/acceptInvation", ReplyAction="http://tempuri.org/IService/acceptInvationResponse")]
        System.Threading.Tasks.Task<string> acceptInvationAsync(string userNameSender, string userNameFriend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getMessages", ReplyAction="http://tempuri.org/IService/getMessagesResponse")]
        string[][] getMessages(string userNameSender, string userNameFriend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getMessages", ReplyAction="http://tempuri.org/IService/getMessagesResponse")]
        System.Threading.Tasks.Task<string[][]> getMessagesAsync(string userNameSender, string userNameFriend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getFriendsListWithMessage", ReplyAction="http://tempuri.org/IService/getFriendsListWithMessageResponse")]
        string[] getFriendsListWithMessage(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getFriendsListWithMessage", ReplyAction="http://tempuri.org/IService/getFriendsListWithMessageResponse")]
        System.Threading.Tasks.Task<string[]> getFriendsListWithMessageAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getGames", ReplyAction="http://tempuri.org/IService/getGamesResponse")]
        string[] getGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getGames", ReplyAction="http://tempuri.org/IService/getGamesResponse")]
        System.Threading.Tasks.Task<string[]> getGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getImageGame", ReplyAction="http://tempuri.org/IService/getImageGameResponse")]
        byte[] getImageGame(string game_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getImageGame", ReplyAction="http://tempuri.org/IService/getImageGameResponse")]
        System.Threading.Tasks.Task<byte[]> getImageGameAsync(string game_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/createRoom", ReplyAction="http://tempuri.org/IService/createRoomResponse")]
        string createRoom(string user_creator, string game, string room_name, string password, int membersNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/createRoom", ReplyAction="http://tempuri.org/IService/createRoomResponse")]
        System.Threading.Tasks.Task<string> createRoomAsync(string user_creator, string game, string room_name, string password, int membersNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getRooms", ReplyAction="http://tempuri.org/IService/getRoomsResponse")]
        string[][] getRooms(string game_user, string game_or_user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getRooms", ReplyAction="http://tempuri.org/IService/getRoomsResponse")]
        System.Threading.Tasks.Task<string[][]> getRoomsAsync(string game_user, string game_or_user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/joinRoom", ReplyAction="http://tempuri.org/IService/joinRoomResponse")]
        string joinRoom(int room_id, string user_name, bool checkOnlyStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/joinRoom", ReplyAction="http://tempuri.org/IService/joinRoomResponse")]
        System.Threading.Tasks.Task<string> joinRoomAsync(int room_id, string user_name, bool checkOnlyStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/roomExit", ReplyAction="http://tempuri.org/IService/roomExitResponse")]
        string roomExit(string user_name, int room_id, bool membersMax);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/roomExit", ReplyAction="http://tempuri.org/IService/roomExitResponse")]
        System.Threading.Tasks.Task<string> roomExitAsync(string user_name, int room_id, bool membersMax);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/roomSetting", ReplyAction="http://tempuri.org/IService/roomSettingResponse")]
        string roomSetting(string operation, string operation_object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/roomSetting", ReplyAction="http://tempuri.org/IService/roomSettingResponse")]
        System.Threading.Tasks.Task<string> roomSettingAsync(string operation, string operation_object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getMembers", ReplyAction="http://tempuri.org/IService/getMembersResponse")]
        string[][] getMembers(int room_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getMembers", ReplyAction="http://tempuri.org/IService/getMembersResponse")]
        System.Threading.Tasks.Task<string[][]> getMembersAsync(int room_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getMessagesInRoom", ReplyAction="http://tempuri.org/IService/getMessagesInRoomResponse")]
        string[][] getMessagesInRoom(int room_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getMessagesInRoom", ReplyAction="http://tempuri.org/IService/getMessagesInRoomResponse")]
        System.Threading.Tasks.Task<string[][]> getMessagesInRoomAsync(int room_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/messagesRead", ReplyAction="http://tempuri.org/IService/messagesReadResponse")]
        string messagesRead(string sender, string recipient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/messagesRead", ReplyAction="http://tempuri.org/IService/messagesReadResponse")]
        System.Threading.Tasks.Task<string> messagesReadAsync(string sender, string recipient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUnreadMessagesCount", ReplyAction="http://tempuri.org/IService/getUnreadMessagesCountResponse")]
        int getUnreadMessagesCount(string sender, string recipient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/getUnreadMessagesCount", ReplyAction="http://tempuri.org/IService/getUnreadMessagesCountResponse")]
        System.Threading.Tasks.Task<int> getUnreadMessagesCountAsync(string sender, string recipient);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : GameChat.Server.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<GameChat.Server.IService>, GameChat.Server.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string login(string Email, string password) {
            return base.Channel.login(Email, password);
        }
        
        public System.Threading.Tasks.Task<string> loginAsync(string Email, string password) {
            return base.Channel.loginAsync(Email, password);
        }
        
        public string accountCheckForReg(string userName, string Email) {
            return base.Channel.accountCheckForReg(userName, Email);
        }
        
        public System.Threading.Tasks.Task<string> accountCheckForRegAsync(string userName, string Email) {
            return base.Channel.accountCheckForRegAsync(userName, Email);
        }
        
        public string FriendAdd(string userNameSender, string userNameRecepient) {
            return base.Channel.FriendAdd(userNameSender, userNameRecepient);
        }
        
        public System.Threading.Tasks.Task<string> FriendAddAsync(string userNameSender, string userNameRecepient) {
            return base.Channel.FriendAddAsync(userNameSender, userNameRecepient);
        }
        
        public string Reg(string userName, string Email, string password) {
            return base.Channel.Reg(userName, Email, password);
        }
        
        public System.Threading.Tasks.Task<string> RegAsync(string userName, string Email, string password) {
            return base.Channel.RegAsync(userName, Email, password);
        }
        
        public string getAccount(string Email) {
            return base.Channel.getAccount(Email);
        }
        
        public System.Threading.Tasks.Task<string> getAccountAsync(string Email) {
            return base.Channel.getAccountAsync(Email);
        }
        
        public string[] getFriendList(string userName, string type) {
            return base.Channel.getFriendList(userName, type);
        }
        
        public System.Threading.Tasks.Task<string[]> getFriendListAsync(string userName, string type) {
            return base.Channel.getFriendListAsync(userName, type);
        }
        
        public string unfriend(string userNameSender, string userNameFriend) {
            return base.Channel.unfriend(userNameSender, userNameFriend);
        }
        
        public System.Threading.Tasks.Task<string> unfriendAsync(string userNameSender, string userNameFriend) {
            return base.Channel.unfriendAsync(userNameSender, userNameFriend);
        }
        
        public string acceptInvation(string userNameSender, string userNameFriend) {
            return base.Channel.acceptInvation(userNameSender, userNameFriend);
        }
        
        public System.Threading.Tasks.Task<string> acceptInvationAsync(string userNameSender, string userNameFriend) {
            return base.Channel.acceptInvationAsync(userNameSender, userNameFriend);
        }
        
        public string[][] getMessages(string userNameSender, string userNameFriend) {
            return base.Channel.getMessages(userNameSender, userNameFriend);
        }
        
        public System.Threading.Tasks.Task<string[][]> getMessagesAsync(string userNameSender, string userNameFriend) {
            return base.Channel.getMessagesAsync(userNameSender, userNameFriend);
        }
        
        public string[] getFriendsListWithMessage(string userName) {
            return base.Channel.getFriendsListWithMessage(userName);
        }
        
        public System.Threading.Tasks.Task<string[]> getFriendsListWithMessageAsync(string userName) {
            return base.Channel.getFriendsListWithMessageAsync(userName);
        }
        
        public string[] getGames() {
            return base.Channel.getGames();
        }
        
        public System.Threading.Tasks.Task<string[]> getGamesAsync() {
            return base.Channel.getGamesAsync();
        }
        
        public byte[] getImageGame(string game_name) {
            return base.Channel.getImageGame(game_name);
        }
        
        public System.Threading.Tasks.Task<byte[]> getImageGameAsync(string game_name) {
            return base.Channel.getImageGameAsync(game_name);
        }
        
        public string createRoom(string user_creator, string game, string room_name, string password, int membersNumber) {
            return base.Channel.createRoom(user_creator, game, room_name, password, membersNumber);
        }
        
        public System.Threading.Tasks.Task<string> createRoomAsync(string user_creator, string game, string room_name, string password, int membersNumber) {
            return base.Channel.createRoomAsync(user_creator, game, room_name, password, membersNumber);
        }
        
        public string[][] getRooms(string game_user, string game_or_user) {
            return base.Channel.getRooms(game_user, game_or_user);
        }
        
        public System.Threading.Tasks.Task<string[][]> getRoomsAsync(string game_user, string game_or_user) {
            return base.Channel.getRoomsAsync(game_user, game_or_user);
        }
        
        public string joinRoom(int room_id, string user_name, bool checkOnlyStatus) {
            return base.Channel.joinRoom(room_id, user_name, checkOnlyStatus);
        }
        
        public System.Threading.Tasks.Task<string> joinRoomAsync(int room_id, string user_name, bool checkOnlyStatus) {
            return base.Channel.joinRoomAsync(room_id, user_name, checkOnlyStatus);
        }
        
        public string roomExit(string user_name, int room_id, bool membersMax) {
            return base.Channel.roomExit(user_name, room_id, membersMax);
        }
        
        public System.Threading.Tasks.Task<string> roomExitAsync(string user_name, int room_id, bool membersMax) {
            return base.Channel.roomExitAsync(user_name, room_id, membersMax);
        }
        
        public string roomSetting(string operation, string operation_object) {
            return base.Channel.roomSetting(operation, operation_object);
        }
        
        public System.Threading.Tasks.Task<string> roomSettingAsync(string operation, string operation_object) {
            return base.Channel.roomSettingAsync(operation, operation_object);
        }
        
        public string[][] getMembers(int room_id) {
            return base.Channel.getMembers(room_id);
        }
        
        public System.Threading.Tasks.Task<string[][]> getMembersAsync(int room_id) {
            return base.Channel.getMembersAsync(room_id);
        }
        
        public string[][] getMessagesInRoom(int room_id) {
            return base.Channel.getMessagesInRoom(room_id);
        }
        
        public System.Threading.Tasks.Task<string[][]> getMessagesInRoomAsync(int room_id) {
            return base.Channel.getMessagesInRoomAsync(room_id);
        }
        
        public string messagesRead(string sender, string recipient) {
            return base.Channel.messagesRead(sender, recipient);
        }
        
        public System.Threading.Tasks.Task<string> messagesReadAsync(string sender, string recipient) {
            return base.Channel.messagesReadAsync(sender, recipient);
        }
        
        public int getUnreadMessagesCount(string sender, string recipient) {
            return base.Channel.getUnreadMessagesCount(sender, recipient);
        }
        
        public System.Threading.Tasks.Task<int> getUnreadMessagesCountAsync(string sender, string recipient) {
            return base.Channel.getUnreadMessagesCountAsync(sender, recipient);
        }
    }
}
